const allPage = [
  [
    {
      t: "Sales reports",
      t1: "Detailed report to show how your sales performing",
      data: [
        {
          t: "Sales Summary",
          d: "How’z your sales performing?",
          d1: "Shows sales summary for a given date range",
          path: "salesSummary",
          apiPath: "report/sales/saleSummary",
          table: [
            { width: "18%", title: "Date", name: "date" },
            {
              width: "18%",
              title: "product_name",
              name: "invoice_count",
              align: "right",
            },
            {
              width: "18%",
              title: "Credit",
              name: "credit_sales",
              align: "right",
              sum: true,
            },
            {
              width: "18%",
              title: "Cash",
              name: "paid_sales",
              align: "right",
              sum: true,
            },
            {
              width: "18%",
              title: "Total",
              name: "total_sales",
              align: "right",
              sum: true,
            },
          ],
        },
        {
          t: "Sales Invoices",
          d: "What all sales invoices are recorded in my business?",
          d1: "Shows all the sales invoices recorded for a given date range",
          path: "salesInvoices",
          apiPath: "report/sales/salesInvoices",
          table: [
            { width: "15%", title: "Date ", name: "invoice_date" },
            {
              width: "15%",
              title: "Invoice",
              name: "invoice_no",
              align: "right",
            },
            {
              width: "15%",
              title: "Customer",
              name: "customer_name",
              align: "right",
              sum: true,
            },
            {
              width: "15%",
              title: "Credit",
              name: "balance_amount",
              align: "right",
              sum: true,
            },
            {
              width: "15%",
              title: "Cash",
              name: "paid_sales",
              align: "right",
              sum: true,
            },
            {
              width: "15%",
              title: "Total",
              name: "total_amount",
              align: "right",
              sum: true,
            },
          ],
        },
        {
          t: "Sales Rank",
          d: "What all are your best selling and least selling products?",
          d1: "Shows all the products sales performance in descending order for a given date range",
          path: "salesRank",
          apiPath: "report/sales/saleRank",
          table: [
            { width: "15%", title: "Rank ", name: "invoice_date" },
            {
              width: "24%",
              title: "Product",
              name: "product_name",
              align: "right",
            },
            {
              width: "18%",
              title: "Category",
              name: "category",
              align: "right",
            },
            {
              width: "15%",
              title: "Quantity",
              name: "sale_count",
              align: "right",
            },
            {
              width: "15%",
              title: "Total",
              name: "sales_amount",
              align: "right",
              sum: true,
            },
          ],
        },
        {
          t: "Sales Comparison",
          d: "HHow’s your business growing compared to the last period?",
          d1: "Shows sales performance compared with the last time preset counterpart",
          path: "salesComparison",
          apiPath: "report/sales/saleComparison",
          table: [
            { width: "15%", title: "Product", name: "name" },
            {
              width: "24%",
              title: "This Mth",
              name: "current_tenure_stock",
              align: "right",
            },
            {
              width: "18%",
              title: "Category",
              name: "category",
              align: "right",
            },
            {
              width: "15%",
              title: "Quantity",
              name: "sale_count",
              align: "right",
            },
            {
              width: "15%",
              title: "Total",
              name: "sales_amount",
              align: "right",
              sum: true,
            },
          ],
        },
        {
          t: "Profit Analysis",
          d: "How much profit I have made from my business?",
          d1: "Shows your profitability against product, invoice and even customers for a given date range",
          path: "profitAnalysis",
          apiPath: "report/sales/profitAnalysis",
          table: [
            { width: "30%", title: "Product", name: "name" },
            {
              width: "15%",
              title: "Qty",
              name: "count",
              align: "right",
            },
            {
              width: "15%",
              title: "Amount",
              name: "total_amount",
              align: "right",
              sum: true,
            },
            {
              width: "15%",
              title: "Cost | %",
              name: "cost_percent",
              align: "right",
              sum: true,
            },
            {
              width: "15%",
              title: "Profile | %",
              name: "profit_percent",
              align: "right",
              sum: true,
            },
          ],
        },
      ],
    },

    {
      t: "Purchase reports",
      t1: "Detailed report to show how your purchases performing",
      data: [
        {
          t: "Purchase Summary",
          d: "How much profit I have made from my business?",
          d1: "Shows income, expense and profit for a given date range",
          path: "purchaseSummary",
          apiPath: "report/purchase/purchaseSummary",
          table: [
            { width: "18%", title: "Date ", name: "date" },
            {
              width: "18%",
              title: "Invoices",
              name: "invoice_count",
              align: "right",
            },
            {
              width: "18%",
              title: "Credit",
              name: "credit_purchase",
              align: "right",
              sum: true,
            },
            {
              width: "18%",
              title: "Paid",
              name: "paid_purchase",
              align: "right",
              sum: true,
            },
            {
              width: "18%",
              title: "Total",
              name: "total_purchase",
              align: "right",
              sum: true,
            },
          ],
        },
        {
          t: "Purchase Invoices (GRN)",
          d: "How much profit I have made from my business?",
          d1: "Shows income, expense and profit for a given date range",
          path: "purchaseInvoices",
          apiPath: "report/sales/saleSummary",
          table: [
            { width: "18%", title: "Date ", name: "date" },
            {
              width: "18%",
              title: "Invoices",
              name: "invoice_count",
              align: "right",
            },
            {
              width: "18%",
              title: "Credit",
              name: "credit_purchase",
              align: "right",
              sum: true,
            },
            {
              width: "18%",
              title: "Paid",
              name: "paid_sales",
              align: "right",
              sum: true,
            },
            {
              width: "18%",
              title: "Total",
              name: "total_sales",
              align: "right",
              sum: true,
            },
          ],
        },
        {
          t: "Purchase Rank",
          d: "How much profit I have made from my business?",
          d1: "Shows income, expense and profit for a given date range",
          path: "purchaseRank",
          apiPath: "report/purchase/purchaseRank",
        },
        {
          t: "Cost Variance",
          d: "How much profit I have made from my business?",
          d1: "Shows income, expense and profit for a given date range",
          path: "costVariance",
          apiPath: "report/purchase/costVariance",
          table: [
            { width: "18%", title: "Date ", name: "date" },
            {
              width: "18%",
              title: "Supplier",
              name: "invoice_count",
              align: "right",
            },
            {
              width: "18%",
              title: "Qty",
              name: "credit_purchase",
              align: "right",
              sum: true,
            },
            {
              width: "18%",
              title: "Cost",
              name: "paid_sales",
              align: "right",
              sum: true,
            },
            {
              width: "18%",
              title: "Prev Cost",
              name: "total_sales",
              align: "right",
              sum: true,
            },
            {
              width: "18%",
              title: "Variance",
              name: "total_sales",
              align: "right",
              sum: true,
            },
          ],
        },
        {
          t: "Supplier Statement",
          d: "How much profit I have made from my business?",
          d1: "Shows income, expense and profit for a given date range",
          path: "supplierStatement",
          apiPath: "report/purchase/costVariance",
          table: [
            { width: "18%", title: "Date ", name: "date" },
            {
              width: "18%",
              title: "Supplier",
              name: "invoice_count",
              align: "right",
            },
            {
              width: "18%",
              title: "Qty",
              name: "credit_purchase",
              align: "right",
              sum: true,
            },
            {
              width: "18%",
              title: "Cost",
              name: "paid_sales",
              align: "right",
              sum: true,
            },
            {
              width: "18%",
              title: "Prev Cost",
              name: "total_sales",
              align: "right",
              sum: true,
            },
            {
              width: "18%",
              title: "Variance",
              name: "total_sales",
              align: "right",
              sum: true,
            },
          ],
        },
        {
          t: "Supplier List",
          d: "How much profit I have made from my business?",
          d1: "Shows income, expense and profit for a given date range",
          path: "supplierList",
          apiPath: "report/member/memberLists",
        },
      ],
    },

    {
      t: "Aging reports",
      t1: "Detailed report to show how your sales performing",
      data: [
        {
          t: "Inventory Aging Report",
          d: "What all are my inventories and how old are they?",
          d1: "Shows income, expense and profit for a given date range",
          path: "inventoryAging",
          apiPath: "report/sales/saleSummary",
        },
        {
          t: "Aged Payments",
          d: "How much money owed and how old they are?",
          d1: "Shows income, expense and profit for a given date range",
          path: "agedPayments",
          apiPath: "report/sales/saleSummary",
        },
      ],
    },

    // {
    //   t: "Tax reports",
    //   t1: "Detailed report to show how your sales performing",
    //   data: [
    //     {
    //       t: "GSTR1",
    //       d: "How much sales tax do I owe?",
    //       d1: "Shows income, expense and profit for a given date range",
    //       path: "gSTR1",
    //       apiPath: "report/sales/saleSummary",
    //     },
    //     {
    //       t: "GSTR 3B",
    //       d: "How much profit I have made from my business?",
    //       d1: "Shows income, expense and profit for a given date range",
    //       path: "gSTR3B",
    //       apiPath: "report/sales/saleSummary",
    //     },
    //     {
    //       t: "GSTR 1B",
    //       d: "How much profit I have made from my business?",
    //       d1: "Shows income, expense and profit for a given date range",
    //       path: "gSTR1B",
    //       apiPath: "report/sales/saleSummary",
    //     },
    //   ],
    // },
  ],
  [
    {
      t: "Inventory reports",
      t1: "Detailed report to know your inventory position and tracking",
      data: [
        {
          t: "Stock Summary",
          d: "How much profit I have made from my business?",
          d1: "Shows income, expense and profit for a given date range",
          path: "stockSummary",
          apiPath: "report/inventory/stockSummery",
          table: [
            { width: "18%", title: "Date ", name: "date" },
            {
              width: "18%",
              title: "Prodect",
              name: "product_name",
              align: "right",
            },
            {
              width: "18%",
              title: "Opening",
              name: "opening_stock",
              align: "right",
              sum: true,
            },
            {
              width: "18%",
              title: "Value",
              name: "opening_stock_value",
              align: "right",
              sum: true,
            },
            {
              width: "18%",
              title: "Closing",
              name: "current_stock",
              align: "right",
              sum: true,
            },
            {
              width: "18%",
              title: "Value",
              name: "current_stock_value",
              align: "right",
              sum: true,
            },
            {
              width: "18%",
              title: "Movement",
              name: "stock_movement",
              align: "right",
              sum: true,
            },
            {
              width: "18%",
              title: "Value",
              name: "movement_stock_value",
              align: "right",
              sum: true,
            },
          ],
        },
        {
          t: "Stock Trail",
          d: "What stock items came in and out during a given date range?",
          d1: "Shows income, expense and profit for a given date range",
          path: "stockTrail",
          apiPath: "report/inventory/stockTrail",
          table: [
            { width: "18%", title: "Date ", name: "date" },
            {
              width: "18%",
              title: "Prodect",
              name: "product_name",
              align: "right",
            },
            {
              width: "18%",
              title: "Opening",
              name: "opening_stock",
              align: "right",
              sum: true,
            },
            {
              width: "18%",
              title: "Value",
              name: "opening_stock_value",
              align: "right",
              sum: true,
            },
            {
              width: "18%",
              title: "Closing",
              name: "current_stock",
              align: "right",
              sum: true,
            },
            {
              width: "18%",
              title: "Value",
              name: "current_stock_value",
              align: "right",
              sum: true,
            },
            {
              width: "18%",
              title: "Movement",
              name: "stock_movement",
              align: "right",
              sum: true,
            },
            {
              width: "18%",
              title: "Value",
              name: "movement_stock_value",
              align: "right",
              sum: true,
            },
          ],
        },
        {
          t: "Minimum Stock Summary",
          d: "How much profit I have made from my business?",
          d1: "Shows income, expense and profit for a given date range",
          path: "minimumStock",
          apiPath: "report/inventory/minimumStockLevelSummary",
        },
        {
          t: "Stock Adjustment",
          d: "How much profit I have made from my business?",
          d1: "Shows income, expense and profit for a given date range",
          path: "stockAdjustment",
          apiPath: "report/inventory/stockAdjustmentSummary",
          table: [
            { width: "20%", title: "Product", name: "product_name" },
            {
              width: "15%",
              title: "opening",
              name: "product_name",
              align: "right",
            },
            {
              width: "15%",
              title: "Value",
              name: "opening_stock",
              align: "right",
              sum: true,
            },
            {
              width: "15%",
              title: "Closing",
              name: "opening_stock_value",
              align: "right",
              sum: true,
            },
            {
              width: "15%",
              title: "Value",
              name: "current_stock",
              align: "right",
              sum: true,
            },
            {
              width: "15%",
              title: "Movement",
              name: "stock_movement",
              align: "right",
              sum: true,
            },
            {
              width: "15%",
              title: "Value",
              name: "movement_stock_value",
              align: "right",
              sum: true,
            },
          ],
        },
        {
          t: "Stock Rate Card",
          d: "How much profit I have made from my business?",
          d1: "Shows income, expense and profit for a given date range",
          path: "stockRate",
          apiPath: "report/sales/saleSummary",
        },
      ],
    },

    {
      t: "Expense reports",
      t1: "Detailed report to show how your sales performing",
      data: [
        {
          t: "Expense Summary",
          d: "How much profit I have made from my business?",
          d1: "Shows income, expense and profit for a given date range",
          path: "expenseSummary",
          apiPath: "report/sales/saleSummary",
        },
        {
          t: "Expense Transactions",
          d: "How much profit I have made from my business?",
          d1: "Shows income, expense and profit for a given date range",
          path: "expenseTransactions",
          apiPath: "report/sales/saleSummary",
        },
        {
          t: "Expense Category Report",
          d: "How much profit I have made from my business?",
          d1: "Shows income, expense and profit for a given date range",
          path: "expenseCategory",
          apiPath: "report/sales/saleSummary",
        },
        {
          t: "Expense Rank",
          d: "How much profit I have made from my business?",
          d1: "Shows income, expense and profit for a given date range",
          path: "expenseRank",
          apiPath: "report/sales/saleSummary",
        },
      ],
    },

    {
      t: "Cash reports",
      t1: "Detailed report to show how your sales performing",
      data: [
        {
          t: "Cashflow Summary",
          d: "How much actual cash came in and out?",
          d1: "Shows income, expense and profit for a given date range",
          path: "cashflowSummary",
          apiPath: "report/sales/saleSummary",
        },
        {
          t: "Cash Transactions",
          d: "What are the cash transactions and running balance for a selected cash accoun?",
          d1: "Shows income, expense and profit for a given date range",
          path: "cashTransactions",
          apiPath: "report/sales/saleSummary",
        },
        {
          t: "Bank Transactions",
          d: "What are the bank transactions and running balance for a selected bank accoun?",
          d1: "Shows income, expense and profit for a given date range",
          path: "bankTransactions",
          apiPath: "report/sales/saleSummary",
        },
        {
          t: "Aggregator Transactions",
          d: "What are the transactions and running balance for a selected aggregator accoun?",
          d1: "Shows income, expense and profit for a given date range",
          path: "aggregatorTransactions",
          apiPath: "report/sales/saleSummary",
        },
      ],
    },

    // {
    //   t: "Financial reports",
    //   t1: "Detailed report to show how your sales performing",
    //   data: [
    //     {
    //       t: "Profit & Loss",
    //       d: "How much profit I have made from my business?",
    //       d1: "Shows income, expense and profit for a given date range",
    //       path: "profit&",
    //       apiPath: "report/sales/saleSummary",
    //     },
    //     {
    //       t: "Balance Sheet",
    //       d: "How much are my assets and labilites worth?",
    //       d1: "Shows income, expense and profit for a given date range",
    //       path: "balanceSheet",
    //       apiPath: "report/sales/saleSummary",
    //     },
    //     {
    //       t: "Trial Balance",
    //       d: "What is the balace of each ledger account?",
    //       d1: "Shows income, expense and profit for a given date range",
    //       path: "trialBalance",
    //       apiPath: "report/sales/saleSummary",
    //     },
    //   ],
    // },
  ],
];
const favoritesPage = [[], []];
const salesPage = [[], []];
const inventoryPage = [[], []];
const purchasePage = [[], []];
const expensePage = [[], []];
const cashPage = [[], []];
const financePage = [[], []];
const taxPage = [[], []];

export const reportPages = [
  allPage,
  favoritesPage,
  favoritesPage,
  salesPage,
  inventoryPage,
  purchasePage,
  expensePage,
  cashPage,
  financePage,
  taxPage,
];
