name: Docker Image CI

on:
  push:
    branches: [ "jaseel" ]
  pull_request:
    branches: [ "jaseel" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Building Application
      run: |
           npm install
           npm run build -prod
