name: Docker Image CI

on:
  push:
    branches: [ "jaseel" ]
  pull_request:
    branches: [ "jaseel" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: npm i
           npm run build
