name: Docker Image CI

on:
  push:
    branches: [ "jaseel" ]
  pull_request:
    branches: [ "jaseel" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Building Application
    - run: npm i;
           npm run build
